// <auto-generated />
using System;
using DB.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220902215700_seconds")]
    partial class seconds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entities.Mail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("from_email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("from_enable_ssl")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("from_host")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("from_password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("from_port")
                        .HasColumnType("int");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("modify_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("reason")
                        .HasColumnType("longtext");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("to_email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("mails");
                });
#pragma warning restore 612, 618
        }
    }
}
